# LOCAL PERSISTENT SQLITE CONFIG (DEFAULT PROFILE)
spring.datasource.url=jdbc:sqlite:./swapu_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# HIBERNATE SETTINGS
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Flyway is enabled only in production Postgres profile.
spring.flyway.enabled=false
